server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/project_insurance
    username: postgres
    password: dante123
  jpa:
    database: POSTGRESQL
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

---
enviroment: test
spring:
  datasource:
    url: jdbc:h2:mem:project_insurance
    username: test
    password: test
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true