spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/project_insurance
    username: root
    password: dante123
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
